// Generate src/data/ngram.ts — a character bigram language model of legitimate
// domain labels, learned from the Tranco SLDs. Used to score how "word-like" a
// domain label is: real names have common letter pairs; random/DGA strings don't.
// Run: node scripts/gen-ngram.mjs   (after scripts/eval/prep.ts cached Tranco)
import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

const ROOT = resolve(import.meta.dirname, '..')
const lines = readFileSync(resolve(ROOT, 'data-eval/tranco-top.txt'), 'utf8').split(/\r?\n/).filter(Boolean)

// Alphabet: a-z, 0-9, hyphen, plus '^' start and '$' end markers.
const ALPHABET = 'abcdefghijklmnopqrstuvwxyz0123456789-^$'
const idx = Object.fromEntries([...ALPHABET].map((c, i) => [c, i]))
const N = ALPHABET.length
const counts = Array.from({ length: N }, () => new Array(N).fill(0))

function sldOf(domain) {
  const p = domain.toLowerCase().split('.')
  return (p.length >= 2 ? p[p.length - 2] : p[0]).replace(/[^a-z0-9-]/g, '')
}

let trained = 0
for (const d of lines) {
  const s = sldOf(d)
  if (s.length < 2) continue
  const seq = '^' + s + '$'
  for (let i = 1; i < seq.length; i++) {
    const a = idx[seq[i - 1]], b = idx[seq[i]]
    if (a !== undefined && b !== undefined) counts[a][b]++
  }
  trained++
}

// Add-1 (Laplace) smoothing → log P(next | prev). Unseen pairs get a small prob.
const logp = Array.from({ length: N }, () => new Array(N).fill(0))
for (let a = 0; a < N; a++) {
  let row = 0
  for (let b = 0; b < N; b++) row += counts[a][b]
  for (let b = 0; b < N; b++) logp[a][b] = Math.log((counts[a][b] + 1) / (row + N))
}

const out = `// AUTO-GENERATED by scripts/gen-ngram.mjs — do not edit by hand.
// Character bigram language model of legitimate domain labels (learned from
// ${trained} Tranco SLDs). LOGP[a][b] = log P(char b follows char a). Used by
// ngram.ts to score how word-like a label is (low surprise = word-like).
export const ALPHABET = ${JSON.stringify(ALPHABET)}
export const LOGP: number[][] = ${JSON.stringify(logp.map((r) => r.map((v) => +v.toFixed(4))))}
`
writeFileSync(resolve(ROOT, 'src/data/ngram.ts'), out)
console.log(`ngram.ts written: ${N}x${N} bigram model from ${trained} Tranco SLDs`)
