// AUTO-GENERATED by scripts/ml/train.ts — do not edit by hand.
// Tier-1 logistic-regression hybrid. Inference = sigmoid(w·z + b) where
// z = (features - mean) / std. ~19 floats; no runtime dependencies.
// Trained 2026-06-13 on 333 positives + 35000 train negatives.
export const MODEL = {
  features: ["bestSim","nearestVisual","nearestTranspose","homoglyph","mixedScript","homoglyphCount","skelExact","exactCore","embedded","subBrand","tldSuspicious","lureCount","sldLen","digitRatio","hyphenCount","official","simUnofficial","embedLure","subUnofficial"],
  mean: [0.364148, 0.347714, 0.023813, 0.001107, 0.000908, 0.003661, 0.000851, 0.000653, 0.004853, 0.000539, 0.018278, 0.011467, 8.184543, 0.023739, 0.084864, 0.005847, 0.35877, 0.001334, 0.000539],
  std: [0.098147, 0.476245, 0.152466, 0.033252, 0.030123, 0.106087, 0.029168, 0.025542, 0.069497, 0.023216, 0.133956, 0.108839, 3.705053, 0.106703, 0.311296, 0.07624, 0.091277, 0.036499, 0.023216],
  weights: [0.85106, -0.111537, 0.195005, 0.643225, 0.55435, 0.070599, 0.689064, 0.00265, -0.017575, 0.548287, -0.047396, 0.054724, 0.080906, 0.397831, 0.128741, -0.081686, 0.950645, 0.603178, 0.548287],
  bias: -5.381937,
  warnThreshold: 0.940,
  blockThreshold: 0.995,
} as const
